spring:
  profiles:
    active: dev
  application:
    name: study
  cloud:
    nacos:
      config:
        server-addr: nacos.vpcflow.com:8848
        namespace: ecb6f5f4-6b01-461a-b158-1229dd425df2
  arthas:
    enabled: false
  redisson:
    mode: single
    password: Redis123
    pool:
      connTimeout: 2000
      size: 100
      minIdle: 50
      maxActive: 100
    single:
      address: redis://192.168.4.21:30299
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  datasource:
    single:
      url: jdbc:postgresql://localhost:5432/postgres
      driverClassName: org.postgresql.Driver
      username: peter
      password: 123456

mybatis-plus:
  typeAliasesPackage: com.flowyun.study.pmdemo.**.base.entity
  typeEnumsPackage: com.flowyun.study.pmdemo.**.base.entity.em
  global-config:
    sql-parser-cache: false