spring:
  profiles:
    active: dev
  application:
    name: study
  arthas:
    enabled: false
  redisson:
    mode: single
    password: Redis123
    pool:
      connTimeout: 2000
      size: 100
      minIdle: 50
      maxActive: 100
    single:
      address: redis://localhost:6379
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  datasource:
    single:
      url: jdbc:postgresql://localhost:5432/postgres
      driverClassName: org.postgresql.Driver
      username: peter
      password: 123456

mybatis-plus:
  typeAliasesPackage: com.flowyun.study.pmdemo.**.base.entity
  typeEnumsPackage: com.flowyun.study.pmdemo.**.base.entity.em
  global-config:
    sql-parser-cache: false